apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-search
  template:
    metadata:
      labels:
        app: backend-search
    spec:
      containers:
      - name: backend-search
        image: d4nd3/backend-search:latest
        command: ["java", "-Dquarkus.http.host=0.0.0.0", "-jar", "/app/quarkus-run.jar"]
        env:
        - name: QUARKUS_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/journaldb
        - name: QUARKUS_DATASOURCE_USERNAME
          value: journaluser
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: journalpassword
        - name: QUARKUS_HTTP_PORT
          value: "8086"
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: backend-search
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: backend-search