# name: Deploy MySQL to CBH Cloud

# on:
#   workflow_dispatch:

# jobs:
#   deploy-mysql:
#     runs-on: ubuntu-latest

#     steps:
#     # 1. Checkout repo
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     # 2. Deploy MySQL using CBH API
#     - name: Deploy MySQL to CBH Cloud
#       run: |
#         curl -X POST "https://api.cloud.cbh.kth.se/deploy/v2/deployments" \
#         -H "Authorization: Bearer ${{ secrets.CBH_API_KEY }}" \
#         -H "Content-Type: application/json" \
#         -d '{
#           "name": "mysql-db",
#           "image": "mysql:8.0",
#           "ports": [{"port": 3306, "protocol": "TCP"}],
#           "env": [
#             {"name": "MYSQL_ROOT_PASSWORD", "value": "rootpassword"},
#             {"name": "MYSQL_DATABASE", "value": "journaldb"},
#             {"name": "MYSQL_USER", "value": "journaluser"},
#             {"name": "MYSQL_PASSWORD", "value": "journalpassword"}
#           ]
#         }'